apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-agents
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}