apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins
  namespace: jenkins
rules:
  - apiGroups:
      - '*'
    resources:
      - replicationcontrollers
      - events
      - daemonsets
      - services
      - replicasets
      - poddisruptionbudget
      - namespaces
      - podsecuritypolicies
      - jobs
      - deployments/scale
      - pods/log
      - pods
      - secrets
      - podtemplates
      - configmaps
      - endpoints
      - cronjobs
      - persistentvolumeclaims
      - podpreset
      - persistentvolumes
      - pods/exec
      - statefulsets
      - deployments
    verbs:
      - list
      - watch
      - create
      - update
      - patch
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
      - update
      - get
