apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
  namespace: jenkins
data:
  jenkins-admin-password: {{ .Values.jenkins_password }}
  jenkins-admin-user: {{ .Values.jenkins_user }}
type: Opaque
