apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
  namespace: jenkins
data:
  jenkins-admin-password: {{ .Values.jenkins_password | b64enc }}
  jenkins-admin-user: {{ .Values.jenkins_user | b64enc }}
type: Opaque
