apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.account_id }}@{{ .Values.project_id }}.iam.gserviceaccount.com
automountServiceAccountToken: true
