apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: jenkins
  namespace: jenkins
spec:
  gateways:
    - istio-system/{{ .Values.project_id }}-ingress-gateway
  hosts:
    - jenkins.{{ .Values.domain }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: jenkins.jenkins.svc.cluster.local
            port:
              number: 80